# Generated by Django 5.2.17 on 2026-09-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPaymentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_payments', models.PositiveIntegerField(default=0)),
                ('successful_payments', models.PositiveIntegerField(default=0)),
                ('failed_payments', models.PositiveIntegerField(default=0)),
                ('pending_payments', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
    ]
